# Generated by Django 5.2.6 on 2025-10-27 11:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('labels', '0001_initial'),
        ('posts', '0002_post_slug'),
    ]

    operations = [
        migrations.AddField(
            model_name='post',
            name='labels',
            field=models.ManyToManyField(blank=True, related_name='posts', to='labels.label'),
        ),
    ]
